//找职位-搜索职位导航-一级分类
app.constant("firstJobType",[
    {type:1,text:"用户体验"},
    {type:2,text:"研发"},
    {type:3,text:"大数据"}
]);
//找职位-搜索职位导航-二级分类
app.constant("secondJobType",[
    {type:1,name:"产品"},
    {type:2,name:"UI"},
    {type:3,name:"QA"},
    {type:4,name:"Android"},
    {type:5,name:"IOS"},
    {type:6,name:"WEB"},
    {type:7,name:"OP"},
    {type:8,name:"JAVA"},
    {type:9,name:"NLP"},
    {type:10,name:"DM"},
    {type:11,name:"DL"}
]);
//搜索部分所需过滤器
app.constant("search",[

]);